// All actions and reducers in redux need actions
// typing this action names every time you need to use them
// might be tiresome and leads to typos

// This file defines all actions that will be used by this application.

// Register user actions
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';

// login
export const IS_LOGGED_IN_SUCCESS = 'IS_LOGGED_IN_SUCCESS';
export const IS_LOGGED_IN_FAILURE = 'IS_LOGGED_IN_FAILURE';
export const SET_LOGGED_IN_SUCCESS = 'SET_LOGGED_IN_SUCCESS';
export const LOGIN_INPUT_CHANGE = 'LOGIN_INPUT_CHANGE';

// password reset
export const RESET_PASS_INPUT_CHANGE = 'RESET_PASS_INPUT_CHANGE';
export const IS_PASSWORD_RESET_SUCCESS = 'IS_PASSWORD_RESET_SUCCESS';
export const IS_PASSWORD_RESET_ERROR = 'IS_PASSWORD_RESET_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';

// registration
export const IS_REGISTRATION_SUCCESS = 'IS_REGISTRATION_SUCCESS';
export const IS_REGISTRATION_FAILURE = 'IS_REGISTRATION_FAILURE';
export const INPUT_CHANGE = 'INPUT_CHANGE';

// user profile
export const PROFILE_INPUT_CHANGE = 'PROFILE_INPUT_CHANGE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

// BUSINESS
export const LOAD_BUSINESSES_SUCCESS = 'LOAD_BUSINESSES_SUCCESS';
export const LOAD_BUSINESS = 'LOAD_BUSINESS';
export const BUSINESS_REGISTRATION_SUCCESS = 'BUSINESS_REGISTRATION_SUCCESS';
export const BUSINESS_INPUT_CHANGE = 'BUSINESS_INPUT_CHANGE';
export const BUSINESS_REGISTRATION_FAILURE = 'BUSINESS_REGISTRATION_FAILURE';
export const REGISTER_BUSINESS = 'REGISTER_BUSINESS';

//  user business
export const LOAD_USER_BUSINESSES_SUCCESS = 'LOAD_USER_BUSINESSES_SUCCESS';
export const LOAD_USER_BUSINESS = 'LOAD_USER_BUSINESS';
export const DELETE_USER_BUSINESSES_SUCCESS = 'DELETE_USER_BUSINESSES_SUCCESS';
export const VIEW_USER_BUSINESSES_SUCCESS = 'VIEW_USER_BUSINESSES_SUCCESS';

//  BUSINESS PROFILE
export const LOAD_BUSINESS_PROFILE = 'LOAD_BUSINESS_PROFILE';
export const LOAD_BUSINESS_PROFILE_ERROR = 'LOAD_BUSINESS_PROFILE_ERROR';
export const VIEW_BUSINESSES_PROFILE_SUCCESS = 'VIEW_BUSINESSES_PROFILE_SUCCESS';
export const LOAD_BUSINESSES_REVIEWS_SUCCESS = 'LOAD_BUSINESSES_REVIEWS_SUCCESS';
export const LOAD_USER_BUSINESS_ERROR = 'LOAD_USER_BUSINESS_ERROR';

// Business review actions
export const FETCH_BUSINESS_SUCCESS = 'FETCH_BUSINESS_SUCCESS';
export const ON_MODAL_CLOSE = 'ON_MODAL_CLOSE';
export const REVIEW_INPUT_CHANGE = 'REVIEW_INPUT_CHANGE';
