export const REGISTER_USER = 'REGISTER_USER';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const IS_LOGGED_IN_SUCCESS = 'IS_LOGGED_IN_SUCCESS';
export const SET_LOGGED_IN_SUCCESS = 'SET_LOGGED_IN_SUCCESS';
